apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: my-app-namespace
  app.kubernetes.io/instance: my-app-namespace
  app.kubernetes.io/name: my-app-name
